# ***Numpy Practicals Assignment 29 JUNE 2024 by Piyush Gaur***

In [248]:
import numpy as np # type: ignore

#### 1. Create a 3X3 Numpy array with random integers between 1 and 100 then interchange it rows and columns.

In [247]:
a=np.random.randint(1,101,size = (3, 3))
print(a)

print(end='\n')

print(a.T) #transposed matrix


[[10 26 72]
 [27 36 91]
 [38 54 62]]

[[10 27 38]
 [26 36 54]
 [72 91 62]]


---
#### 2. Generate a 1D Numpy array with 10 elements. reshape it into a 2X5 array,then into 5X2 array.   

In [98]:
a=np.arange(1,11)
print(a)
print("\nReshaped array of 2X5")
print(a.reshape(2,5))
print("\nReshaped array of 5X2")
print(a.reshape(5,2))


[ 1  2  3  4  5  6  7  8  9 10]

Reshaped array of 2X5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped array of 5X2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


---
#### 3. Create a 4X4 Numpy array with random float values. Add a border of zeroes around it, resulting in a 6X6 array.

In [99]:
random_array = np.random.uniform(1, 17, (4, 4))

bordered_array = np.pad(random_array, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array:")
print(random_array)
print("\n6x6 array with border of zeroes:")
print(bordered_array)

Original 4x4 array:
[[ 7.08346232  1.03522482  7.33877758  6.31447369]
 [13.50672526 11.3055324   3.73343439 11.03041724]
 [ 6.28186138  8.20872406 10.67663297  8.17988621]
 [ 2.08141947 12.57073606  1.67198609 15.68047406]]

6x6 array with border of zeroes:
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          7.08346232  1.03522482  7.33877758  6.31447369  0.        ]
 [ 0.         13.50672526 11.3055324   3.73343439 11.03041724  0.        ]
 [ 0.          6.28186138  8.20872406 10.67663297  8.17988621  0.        ]
 [ 0.          2.08141947 12.57073606  1.67198609 15.68047406  0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


---
#### 4. Using Numpy create an array of integers from 10 to 60 with a step of 5.

In [103]:
np.arange(10,61,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

---
#### 5. Create a numpy array of strings['python','numpy','pandas'].Apply different case transfomation(uppercase, lowercase, title etc) to each element.

In [252]:
a=np.array(['python','numpy','pandas'])
print(a)
print("\nUppercase")
print(np.char.upper(a))
print("\nLowercase")
print(np.char.lower(a))
print("\nTitle Case")
print(np.char.capitalize(a))

['python' 'numpy' 'pandas']

Uppercase
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase
['python' 'numpy' 'pandas']

Title Case
['Python' 'Numpy' 'Pandas']


---
#### 6. Generate a Numpy array of words.Insert a space between each characters of every word in the array.

In [139]:
string ="Piyush Gaur Loves data analytics"
a=string.split()
print("Original words:")
print(np.array(a))
print("\nWords with spaces between characters:")
r=np.char.join(' ',a)
print(r)




Original words:
['Piyush' 'Gaur' 'Loves' 'data' 'analytics']

Words with spaces between characters:
['P i y u s h' 'G a u r' 'L o v e s' 'd a t a' 'a n a l y t i c s']


---
#### 7. Create two 2d numpy array and perform element wise addition,subtraction,multiplication and division.

In [177]:
arr1=np.random.randint(1,21,(4,4))
arr2=np.random.randint(1,21,(4,4))
print("arr1\n", arr1)
print('\n')
print("arr2\n", arr2)

print("\nAddition")
print(arr1+arr2)

print("\nSubtraction")
print(arr1-arr2)

print("\nMultplication")
print(arr1*arr2)

print("\nDivision")
print(arr1/arr2)

arr1
 [[ 5  5  3  9]
 [ 4 18 13 10]
 [15  6 10 10]
 [ 8 18  5  3]]


arr2
 [[ 3 11 12  9]
 [ 7  8  9 19]
 [15 10  8  9]
 [13 11  6 12]]

Addition
[[ 8 16 15 18]
 [11 26 22 29]
 [30 16 18 19]
 [21 29 11 15]]

Subtraction
[[ 2 -6 -9  0]
 [-3 10  4 -9]
 [ 0 -4  2  1]
 [-5  7 -1 -9]]

Multplication
[[ 15  55  36  81]
 [ 28 144 117 190]
 [225  60  80  90]
 [104 198  30  36]]

Division
[[1.66666667 0.45454545 0.25       1.        ]
 [0.57142857 2.25       1.44444444 0.52631579]
 [1.         0.6        1.25       1.11111111]
 [0.61538462 1.63636364 0.83333333 0.25      ]]


---
#### 8. Use numpy to create 5X5 identity matrix,then extract its diagonal.

In [246]:
identity_matrix = np.eye(5,dtype=int)
diagonal = np.diag(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal of the Identity Matrix:")
print(diagonal)


5x5 Identity Matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Diagonal of the Identity Matrix:
[1 1 1 1 1]


---
#### 9. Generate a Numpy array of 100 random integers between 0 to 1000. find and display prime numbers in the array.

In [197]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

random_integers = np.random.randint(0, 1001, size=100)

prime_numbers = [num for num in random_integers if is_prime(num)]

print("Array of 100 random integers between 0 and 1000:")
print(random_integers)
print("\nPrime numbers in the array:")
print(prime_numbers)


Array of 100 random integers between 0 and 1000:
[809 737 745 137 141 690 525 942 206 602 979 888 273 518 699 330 832  27
 687 683 789 898 927 905  33 422 754 220  25 344 506 875 257 321 840 291
 418 556 775 219 672  49 540 740 626 996 615 288 365 418 916 566  96 393
 783 520 709 382 280 930  79 131 834 966 479 880 877 814 477 172 967 562
 672  41 998 508  21 301 506 656 256 399 949  21  51 454 675  74 722 643
 703  54 243  84 805 172 968 904 167 999]

Prime numbers in the array:
[809, 137, 683, 257, 709, 79, 131, 479, 877, 967, 41, 643, 167]


---
#### 10. Create a Numpy array representing the daily temperatures for a month.calculate and display the weekly average.

In [263]:
import pprint
arr1=np.random.uniform(20,41,(4,7))
print("Random 2D array daily temperature for a month of 30 days\n")
pprint.pprint(np.array(arr1))
print("\nThe Weekly Average")
pprint.pprint(np.mean(arr1,axis=1))


Random 2D array daily temperature for a month of 30 days

array([[26.86130158, 38.6571426 , 34.49130784, 31.91762422, 32.69529736,
        35.51666999, 37.3867831 ],
       [36.33231444, 26.86846966, 20.12067544, 33.14367589, 20.55162086,
        39.27813133, 36.32752888],
       [21.04230297, 22.53654997, 20.41342291, 33.35242172, 29.6799533 ,
        27.65793059, 26.13227037],
       [27.38567871, 38.0871043 , 25.56584201, 26.01986962, 32.19936824,
        20.53522591, 32.31185489]])

The Weekly Average
array([33.93230381, 30.37463093, 25.83069312, 28.87213481])
